<a href="https://colab.research.google.com/github/TAEJIN-KANG/-001-/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_20248191_%EA%B0%95%ED%83%9C%EC%A7%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np

# 랜덤 씨드 값 설정 사용X
#random.seed(85)

# 로또 번호를 저장할 리스트
lotto_numbers = []

# 3회 반복하여 로또 번호 생성
for _ in range(3):
    # 1부터 45까지의 숫자 생성
    numbers = list(range(1, 46))

    # 랜덤하게 섞기
    random.shuffle(numbers)

    # 첫 6개의 숫자 슬라이싱하여 리스트에 추가
    lotto_numbers.append(numbers[:6])

# 2차원 배열로 변환
lotto = np.array(lotto_numbers)

# 결과 출력
print("로또 번호:\n", lotto)

로또 번호:
 [[ 3 38 34 29  2 14]
 [32 25 36 18  3 23]
 [ 6 21 39  1 24  8]]


In [ ]:
import numpy as np
# 3차원 배열의 크기를 지정합니다.
shape = (3, 3, 6)
# 3차원 배열을 생성합니다.
arr = np.random.randint(0, 20, shape)
# 3차원 배열을 출력합니다.
print(arr)

[[[ 8 14 15  1  1 17]
  [ 3 12 16  5  9 19]
  [ 9 15  5  1 12 19]]

 [[12 16  4 19 16 18]
  [15  5  3 11  1  9]
  [ 5 10  8  5  8 17]]

 [[ 4 17 14  2  0 18]
  [15 15  8  9  8  0]
  [11  6  4  8  3  7]]]


In [ ]:
import numpy as np
# 2차원 배열의 크기를 지정합니다.
shape = (5, 6)
# 2차원 배열을 생성합니다.
arr = np.random.randint(0, 100, shape)
# 2차원 배열을 출력합니다.
print(arr)

[[70 58 82 68 39 68]
 [91 67 20 35  1 53]
 [51 41 43 88 80 72]
 [43 41 69 65 72 91]
 [89 89 26 13 59 24]]


In [ ]:
import numpy as np

# 0부터 47까지의 값을 생성
temp = np.arange(48)

# 랜덤하게 섞기
np.random.shuffle(temp)

# 3차원 배열로 변환 (4, 3, 4)
array_3d = temp.reshape((4, 3, 4))

# 결과 출력
print("3차원 배열:\n", array_3d)

3차원 배열:
 [[[18  8 34 21]
  [22 39 45 28]
  [47 13 16 40]]

 [[27  3 36 46]
  [24 31  9 12]
  [25 32 37 43]]

 [[17 41 19 15]
  [ 6 30 26 42]
  [ 4 10  0 35]]

 [[20 14  1 29]
  [23  2  5 38]
  [11 33  7 44]]]


In [ ]:
import numpy as np

# 0부터 47까지의 값을 생성
temp = np.arange(48)

# 랜덤하게 섞기
np.random.shuffle(temp)

# 2차원 배열로 변환 (6, 8)
array_2d = temp.reshape((6, 8))

# 결과 출력
print("2차원 배열:\n", array_2d)

2차원 배열:
 [[ 4 28  2 12 25 22 29 39]
 [17 14 13 32  9 27 31 37]
 [36 47 20 43 11 30 35  0]
 [ 1 41  3 45 18 15 38  6]
 [ 8 21 19 23 33 16 24 46]
 [26 44  7 10  5 42 34 40]]
